#include <vcl.h>
#include <tchar.h>
#include <math.h>
#include <mmsystem.h>
#include <winioctl.h>
#include <utilcls.h>
#include <shlobj.h>
#include <shlwapi.h>
#include <memory>
#include <algorithm>
#include <VersionHelpers.h>
#include <RegularExpressions.hpp>
#include <System.Win.Registry.hpp>
#include <System.StrUtils.hpp>
#include <System.DateUtils.hpp>
#include <System.IOUtils.hpp>
#include <System.NetEncoding.hpp>
#include <System.Zip.hpp>
#include <Vcl.FileCtrl.hpp>
#include <Vcl.Clipbrd.hpp>
#include <Vcl.Direct2D.hpp>
#include <Vcl.Imaging.pngimage.hpp>
#include <Vcl.Imaging.GIFImg.hpp>
